site_name: RepChain V2.0

nav: 
  - 首页: index.md
  - 功能介绍: RepChain-2.0.md
  - 安装部署: deploy.md
    

theme:
  name: material
  palette:
      - scheme: default
        primary: green 
        toggle:
            icon: material/weather-night
            name: Switch to dark mode
      - scheme: slate
        primary: red
        toggle:
            icon: material/weather-sunny
            name: Switch to light mode
  favicon: img/favicon.ico
  logo: img/favicon.ico
  language: zh
  features:
    - content.code.annotate
    - search.highlight
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list

plugins:
    - search:

copyright: Copyright &copy; 2021-2022 RepChain V2.0
